
com:
  sothawo:
    foodpoi:
      elasticsearchHost: "localhost:9200"
      elasticsearchProxy: "localhost:8080"

logging.level:
  root: warn
  com.sothawo:
    mapjfx: warn
    foodpoi: debug
  org.springframework:
    data: debug
    data.elasticsearch: debug
    elasticsearch.client.WIRE: trace
